modLoader="javafml"
loaderVersion="${loader_version_range_forge}"
issueTrackerURL="${issues_url}"

license="${license_name}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage_url}"
logoFile="icon.png"
authors="${mod_author}"
description='''
${description}
'''
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range_forge}"
    ordering="NONE"
    side="BOTH"
