# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[36,)"
license = "tr7zw Protective License"

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
issueTrackerURL="https://github.com/tr7zw/PaperDoll/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
modId = "paperdoll"
version = "1.1.1"
displayName = "PaperDoll"
logoFile="icon.png" #optional
authors="tr7zw" #optional
description = '''
Shows a small preview of the player in a corner of the screen.
'''

[[dependencies.paperdoll]] #optional
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="CLIENT"
# Here's another dependency
[[dependencies.paperdoll]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,)"
    ordering="NONE"
    side="CLIENT"
